platform :ios, '8.4'

source 'https://github.com/CocoaPods/Specs.git'

workspace 'loadtest'
xcodeproj 'loadtest'

use_frameworks!
pod 'Parse'
pod 'ParseUI'
#pod 'Spring'
#
pod 'AFNetworking'
pod 'ORStackView'
pod 'SwiftyJSON'
pod 'SnapKit'
